define("discourse/plugins/discourse-blizzard-plugin/admin/templates/components/b-notification-message",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"8Sbcu5N3",block:'[[[41,[30,0,["currentUser","employee_flag"]],[[[1,"  "],[10,"label"],[12],[1,"\\n    "],[10,0],[14,0,"b-notification-message-label"],[12],[1,"\\n      "],[1,[28,[35,1],["admin.blizzard.notification_message"],null]],[1,"\\n    "],[13],[1,"\\n  "],[13],[1,"\\n  "],[1,[28,[35,2],null,[["value","class","placeholder"],[[30,0,["message"]],"b-notification-message",[28,[37,1],["admin.blizzard.notification_message_placeholder"],null]]]]],[1,"\\n"]],[]],[[[1,"  "],[1,[28,[35,1],["admin.blizzard.notification_message_not_employee"],null]],[1,"\\n"]],[]]]],[],false,["if","i18n","textarea"]]',moduleName:"discourse/plugins/discourse-blizzard-plugin/admin/templates/components/b-notification-message.hbs",isStrictMode:!1})})),define("discourse/plugins/discourse-blizzard-plugin/admin/templates/components/category-realm-checkbox",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"iUU32jzj",block:'[[[10,"label"],[12],[1,[28,[35,0],["admin.blizzard.category_realm"],null]],[13],[1,"\\n"],[10,0],[14,0,"controls"],[12],[1,"\\n  "],[1,[28,[35,1],null,[["value","nameProperty","content","onChange"],[[30,0,["category","custom_fields","is_realm"]],"name",[30,0,["content"]],[28,[37,2],[[30,0],[28,[37,3],[[30,0,["category","custom_fields","is_realm"]]],null]],null]]]]],[1,"\\n"],[13]],[],false,["i18n","combo-box","action","mut"]]',moduleName:"discourse/plugins/discourse-blizzard-plugin/admin/templates/components/category-realm-checkbox.hbs",isStrictMode:!1})})),define("discourse/plugins/discourse-blizzard-plugin/admin/templates/connectors/admin-user-below-names/blizzard-fields",["exports","@ember/template-factory"],(function(e,t){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=(0,t.createTemplateFactory)({id:"WcfEQW/G",block:'[[[10,0],[14,0,"display-row bnet-id"],[12],[1,"\\n  "],[10,0],[14,0,"field"],[12],[1,"\\n    Battle.net ID\\n  "],[13],[1,"\\n  "],[10,0],[14,0,"value"],[12],[1,"\\n    "],[1,[28,[35,0],[[30,0,["user","bnet_id"]]],null]],[1,"\\n  "],[13],[1,"\\n"],[13],[1,"\\n\\n"],[10,0],[14,0,"display-row battletag"],[12],[1,"\\n  "],[10,0],[14,0,"field"],[12],[1,"\\n    BattleTag\\n  "],[13],[1,"\\n  "],[10,0],[14,0,"value"],[12],[1,"\\n    "],[1,[28,[35,0],[[30,0,["user","battletag"]]],null]],[1,"\\n  "],[13],[1,"\\n"],[13]],[],false,["dash-if-empty"]]',moduleName:"discourse/plugins/discourse-blizzard-plugin/admin/templates/connectors/admin-user-below-names/blizzard-fields.hbs",isStrictMode:!1})})),define("discourse/plugins/discourse-blizzard-plugin/components/category-realm-checkbox",["exports","@ember/component","I18n"],(function(e,t,s){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default=t.default.extend({tagName:"",content:[{id:null,name:s.default.t("realms.select.not")},{id:"true",name:s.default.t("realms.select.normal")},{id:"classic",name:s.default.t("realms.select.classic")}]})})),define("discourse/plugins/discourse-blizzard-plugin/initializers/customize-admin-widgets",["exports","rsvp","discourse/lib/plugin-api","discourse/models/composer","discourse/models/topic","discourse-common/utils/decorators","I18n","discourse/plugins/discourse-blizzard-plugin/discourse/components/modal/blizzard-add-user-note"],(function(e,t,s,o,n,i,a,r){"use strict"
Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0
e.default={name:"customize-admin-widgets",initialize(e){const l=e.lookup("service:modal");(0,s.withPluginApi)("0.8.17",(s=>{const{h:c}=s
s.modifyClass("model:admin-user",{pluginId:"blizzard",unsuspend(){const e=this._super
return this.addNote((()=>e.call(this)))},unsilence(){const e=this._super
return this.addNote((()=>e.call(this)))},addNote(e){return l.show(r.default,{model:{user:this,callback:e}}),t.Promise.resolve(this)}}),s.modifyClass("component:reviewable-item",{pluginId:"blizzard",clientEdit(t,s){this.store.find("post",t.post_id).then((t=>{n.default.find(t.topic_id,{}).then((i=>{const r=n.default.create(i)
if(t.set("topic",r),!this.currentUser){return e.lookup("service:dialog").alert(a.default.t("post.controls.edit_anonymous"))}if(!t.can_edit)return!1
const l={post:t,action:o.default.EDIT,draftKey:t.get("topic.draft_key"),draftSequence:t.get("topic.draft_sequence"),skipDraftCheck:!0,skipJumpOnSave:!0}
return e.lookup("service:composer").open(l),s()}))}))}}),s.decorateWidget("poster-name:after",(e=>{let t=[],s=e.attrs.userCustomFields
if(s&&(s.battletag&&t.push(c("div.battle-tag",s.battletag)),s.bnet_id&&t.push(c("div.bnet-id",s.bnet_id))),e.attrs.created_ip_address&&t.push(c("div.created-ip-address",{},[c("a",{href:"https://geoip.battle.net/lookup/"+encodeURI(e.attrs.created_ip_address),target:"_blank"},[String(e.attrs.created_ip_address)])])),t.length)return c("div.staff-info",t)}))
let d=dt7948.p({pluginId:"blizzard",reasons:e=>e.map((e=>({id:e,name:a.default.t(`admin.${e}`)}))),setReason(){this.isCustomReason?this.set("reason",this.customReason):this.set("reason",this.selectedReason)},didInsertElement(){this._super(),"silence"===this.penaltyType?this.set("reasonKeys",["common.cms.report.ADVERTISING","common.cms.report.HARASSMENT","common.cms.report.INAPPROPRIATE","common.cms.report.REAL_LIFE_THREATS","common.cms.report.SPAMMING","common.cms.report.TROLLING","common.cms.report.OTHER"]):this.set("reasonKeys",["common.cms.report.SPAMMING","common.cms.report.SPAMMING_TROLLING","common.cms.report.REAL_LIFE_THREATS","common.cms.report.ILLEGAL","common.cms.report.ADVERTISING","common.cms.report.ADVERTISING_STRADING","common.cms.report.RACIAL_HATRED","common.cms.report.RELIGION_HATRED","common.cms.report.IN_GAME","common.cms.report.OBSCENE_LANGUAGE","common.cms.report.HARASSMENT","common.cms.report.OTHER","common.cms.report.NOT_SPECIFIED","common.cms.report.TROLLING"]),this.set("selectedReason","common.cms.report.OTHER"),this.setReason()}},[["method","reasons",[(0,i.default)("reasonKeys")]]])
s.modifyClass("component:admin-penalty-reason",d)}))}}}))

//# sourceMappingURL=discourse-blizzard-plugin_admin-c28ca03777fee859ebc4fea3e6e93866434a97e5e95c5e0b686092521cc51ca4.map
//!

;
